//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.SoapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapService.ISoapService")]
    public interface ISoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/GetData", ReplyAction="http://tempuri.org/ISoapService/GetDataResponse")]
        string GetData(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/GetData", ReplyAction="http://tempuri.org/ISoapService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/CreateNewAmbulatoryPatientTicket", ReplyAction="http://tempuri.org/ISoapService/CreateNewAmbulatoryPatientTicketResponse")]
        string CreateNewAmbulatoryPatientTicket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapService/CreateNewAmbulatoryPatientTicket", ReplyAction="http://tempuri.org/ISoapService/CreateNewAmbulatoryPatientTicketResponse")]
        System.Threading.Tasks.Task<string> CreateNewAmbulatoryPatientTicketAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoapServiceChannel : ConsoleClient.SoapService.ISoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapServiceClient : System.ServiceModel.ClientBase<ConsoleClient.SoapService.ISoapService>, ConsoleClient.SoapService.ISoapService {
        
        public SoapServiceClient() {
        }
        
        public SoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string input) {
            return base.Channel.GetData(input);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string input) {
            return base.Channel.GetDataAsync(input);
        }
        
        public string CreateNewAmbulatoryPatientTicket() {
            return base.Channel.CreateNewAmbulatoryPatientTicket();
        }
        
        public System.Threading.Tasks.Task<string> CreateNewAmbulatoryPatientTicketAsync() {
            return base.Channel.CreateNewAmbulatoryPatientTicketAsync();
        }
    }
}
